version: '3.7'

services:
  devcontainer:
    container_name: devcontainer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VARIANT: 1-20-bullseye
        TERRAFORM_VERSION: 1.5.2
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/node/.ssh:ro
    command: sleep infinity
    user: node
    env_file:
      - ./devcontainer.env
